### ISSUE TITLE
Link GitHub repos / organisation account from 'Open Source' section of index.html

### ISSUE THREAD

**Issue by kerstin** [matplotlib/matplotlib.github.com#17]
I was expecting info on where the code is hosted and how one can contribute in the 'Open Source' section of the index page of the project, but there's none listed there. I eventually found my way here via Google.

I saw now there is one link to 'the github tracker' (i.e. the issues of the project's repo on GH) included in the Documentation > Need help? section of the index page, but 'help' was obviously not what I was looking for.

I'd suggest linking to the two most relevant repos  – the one for the project and the other for the website documenting it, i.e. this repo – in the 'Open Source' section of index.html. I could make a pull request if you're accepting contributions? (There's, unfortunately, no README or CONTRIBUTING file with info for potential contributors and the two open issues are rather old...)

**Comment by jenshnielsen** [comment]
Im happy to improve the documentation but all pages of the documentation has a "fork me on github" link in the top right hand corner

**Comment by kerstin** [comment]
Ohh. I just checked the website again – apparently a browser plugin of mine suppresses the GitHub ribbon from displaying! I had no idea, sorry.

It might still make sense to additionally add the info to the Open Source section on the index page? I know I've previously failed to notice 'fork me' ribbons on other projects and other folks might have the same/similar privacy plugins in place, so might miss this too.

It wouldn't need to be long, just a sentence or two?

**Comment by jenshnielsen** [comment]
closed by matplotlib/matplotlib/#5818
