### ISSUE TITLE
Dead image links on cmocean

### ISSUE THREAD

**Issue by endolith** [matplotlib/matplotlib.github.com#26]
https://matplotlib.org/cmocean/

links to

http://gcoos2.tamu.edu/gandalf_data/deployments/tamu/unit_540/plots/sci_water_temp.png
http://gcoos2.tamu.edu/gandalf_data/deployments/tamu/unit_541/plots/sci_water_temp.png

etc but they don't exist

**Comment by tacaswell** [comment]
attn @kthyng

**Comment by kthyng** [comment]
Thanks, I have fixed these in the [new docs](https://matplotlib.org/cmocean/).
