### ISSUE TITLE
"Installing" docs: Canopy distribution is EOL

### ISSUE THREAD

**Issue by Kadabash** [matplotlib/matplotlib.github.com#42]
In the [Installing section](https://matplotlib.org/users/installing.html#scientific-python-distributions) of the documentation, Canopy is listed as a scientific Python distribution for Windows.
However, Canopy seems to have reached end-of-life (see its [download page](https://assets.enthought.com/downloads/) and an [announcement](https://support.enthought.com/hc/en-us/articles/360038600051-Canopy-GUI-end-of-life-transition-to-the-Enthought-Deployment-Manager-EDM-and-Visual-Studio-Code) by Enthought). There seems to be an alternative called "EDM", though the Matplotlib documentation should probably not refer to a product that is no longer available.

I hope this is the correct repository to report this.

**Comment by timhoffm** [comment]
Thanks for the note! This has already been addressed in #15652 and will take effect in the 3.3.0 docs.
