### ISSUE TITLE
Dead link in mandelbrot.py

### ISSUE THREAD

**Issue by boffi** [matplotlib/matplotlib.github.com#43]
The link

`# https://www.ibm.com/developerworks/community/blogs/jfp/entry/My_Christmas_Gift`

in `matplotlib.github.com/3.2.1/gallery/showcase/mandelbrot.py` does not work any more

When you try to access the linked content, IBM tells you

> **Where is the IBM Developer Answers (formerly developerWorks Answers) forum?**
>    The platform was sunset on 30 April 2020. Much of the content was migrated to the IBM Support forum. Links to specific forums will automatically redirect to the IBM Support forum. You can find migrated questions by using the forum’s search mechanism or by choosing the product or topic tag.

I tried to find the linked content using IBM Support forum's search mechanism to no avail.

Thank you ፨ gb

**Comment by QuLogic** [comment]
I think only @rougier could say where that link should go now, or maybe it should just be removed.

**Comment by Kojoley** [comment]
The Wayback Machine has a page snapshot https://web.archive.org/web/20160331171238/https://www.ibm.com/developerworks/community/blogs/jfp/entry/My_Christmas_Gift?lang=en
