### ISSUE TITLE
Replace Axes in Figure with Axes from separate Figure

### ISSUE THREAD

**Issue by d3-worgan** [matplotlib/matplotlib.github.com#44]
Hi, 

I have a problem using matplotlib and am struggling to get to the bottom this. The problem is there are 2 seperate Figure objects displayed on the screen. Each Figure object contains an Axes object. How can I overwrite / replace the Axes object in Figure 1, with the Axes object from Figure 2?

In other words:

1. We have some data called A.
2. We plot the data called A.
3. The plot is returned in a new Figure and displayed.
4. We have some data called B.
5. We plot the data called B.
6. Now we want to copy and overwrite the Axes containing data B into the Axes containing data A

```python
import matplotlib.pyplot as plt
import numpy as np

plt.ion()

# Draw the first figure and plot
x_1 = np.linspace(0, 10*np.pi, 100)
y_1 = np.sin(x_1)

figure_1 = plt.figure()
axes_1 = figure_1.add_subplot(111)
line_1, = axes_1.plot(x_1, y_1, 'b-')
figure_1.canvas.draw()

# Draw the second figure and plot
x_2 = np.linspace(0, 9*np.pi, 100)
y_2 = np.sin(x_2)

figure_2 = plt.figure()
axes_2 = figure_2.add_subplot(111)
line_2 = axes_2.plot(x_2, y_2, 'r-')
figure_2.canvas.draw()

# Now clear figure_1's axes and replace it with figure_2's axis
figure_1.delaxes(axes_1)
figure_1.add_axes(axes_2)
figure_1.canvas.draw()
````

Using the add_axes() method is raising ValueError "The Axes must have been created in the present figure".

Is there a way to detatch the Axes from the current figure so that it can be added to the other one?

**Comment by tacaswell** [comment]
This is the issue track on the deployed docs, not for the library.  In the future please open bug reports at https://github.com/matplotlib/matplotlib/issues and questions about how to use the library at https://discourse.matplotlib.org.

Currently we do not allow Axes (or any artist) to be moved between Figures.  There is currently too much coupling / caching between the parent / child artists that it is impossible for a Artist to be in more than one figure at the same time.  While it is conceptually possible to clean an Artists sufficiently that it could be re-added to a different Figure, it is far simpler to forbid it.
