### ISSUE TITLE
matplotlib.xkcd gallry misses xkcd call

### ISSUE THREAD

**Issue by jakobgager** [matplotlib/matplotlib.github.com#5]
The really really great xkcd homepage of matplotlib somehow misses the respective xkcd calls in the gallery codes. I pressume the whole page is more a nice gimmick instead of a real source, however at least some comment may be appropriate that the listed code will not give you the xkcd styled image.

I'm **really** looking forward to 1.3.0 cause I love the xkcd style :smile:

**Comment by OceanWolf** [comment]
Ooh, just found this repo and curious as to how to how the updating of the docs works, (I currently work to get git set up for another project), but anyway, I see we have not yet closed this issue, has anyone started on this issue yet?  How much of the code gets autogenerated?  I.e. which files can I change, and which not?

**Comment by jenshnielsen** [comment]
@OceanWolf This issue is strictly about the xkcd version of the docs. 

The docs at matplotlib.org/devdocs are automatically build from Travis. You can see how that is done by looking at the .travis.yaml file which contains everything needed to build the docs and push them back to a gppages branch at https://github.com/matplotlib/devdocs

**Comment by jenshnielsen** [comment]
That is to say everything in that repository and thus at matplotlib.org/devdocs is either coming directly from the main matplotlib repository.

**Comment by tacaswell** [comment]
Closing this as wont fix, the xkcd docs were a bit of a joke and are now _way_ out of date.

**Comment by OceanWolf** [comment]
@jenshnielsen Sorry, I asked about two things at once, one my own curiosity, and the other about fixing this issue.  Anyway, after quite a bit of poking, I now think I understand how it all works.  Only the devdocs project has automation in it, the rest of the site gets built on our own boxes and pushed to this repo like any other push, (but without going through a PR).

Anyway, taking a look through the process I see two worrying things...
1. The latest release version of mpl keeps getting modified when we release a new version of mpl, meaning these files develop history unlike the version set version http://www.matplotlib.org/1.4.3/...
2. All of the code gets needlessly repeated.  Fixing this will make resolve this bug easy.

**To solve 2**, normally this would get solved by using the server-side scripting, such as python (php, etcetera), but failing that we can go for client side scripting with javascript to dynamically paste in content surrounding the main page.  This would mean the banner warning about 2.0 and everything else, menus etcetera can go in one file for easy updating.

**To solve 1**, normally I would go for a redirect, something like the following pseudo-code:
```python
try:
  load_page(url)
except PageNotFoundException:
  latest_version = '1.4.3'  # perhaps some auto-detect logic based on looking at directories
  load_page(latest_version + url)  # if this fails it will fall-back to the 404 page
```
But alas we don't have access to any such server side code, not even anything akin to Apache's ``.htaccess``, so the solution to this again comes from javascript.  For the pages that we know will get duplicated (these shouldn't change between versions) we can use javascript to find and load the correct page into the browser.

Thoughts?

@tacaswell I assume you have a script on your machine to do all the auto-update logic, doesn't that update the xkcd stuff at the same time?

I think it would look nice to keep this joke running, if nothing else it serves to show what can get done with xkcd, and it provides an extra entry point to matplotlib, I find it some nice eye-candy :).  Whatever stuff we find easier to fix with js we can do it that way.
