### ISSUE TITLE
sphinxsidebar text overflow

### ISSUE THREAD

**Issue by aitikgupta** [matplotlib/matplotlib.github.com#52]
(logging this issue here since things get lost on gitter very soon)

The `sphinxsidebar` in some pages lets the text overflow, ref:
https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.tight_layout.html
![image](https://user-images.githubusercontent.com/43996118/106022875-4ae4f780-60ec-11eb-9a81-51e06535bede.png)

Possible Solution:
> @brunobeltran: adding overflow_wrap to the appropriate element in the custom mpl css (https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap)
if we increase sidebar width, I assume it would have to be responsive, and that's a pretty big rabbit-hole to go down. on the other hand specifying overflow-wrap would probably be an immediate improvement (and we would probably want it to be set regardless of if we eventually increase the width)

/cc @timhoffm

**Comment by jklymak** [comment]
Our sphinx setup is on the main repo under `docs/` so I'm going to close this here.
