### ISSUE TITLE
Canonicalize redirected pages correctly

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib.github.com#59]
In 3.4.0, we added a redirect for `/tutorials/introductory/customizing.html` from `/users/customizing.html`. The latter file was previously deleted after 2.0.2. When 3.3.4 was latest, we said the canonical link was `2.0.2/users/customizing.html`, but now that _a_ file has returned in that location, the canonical link is to `/stable/users/customizing.html`, which is a only meta-refresh to the right file.

I have _not_ committed these changes. We should decide on what to do here, but if those old files will stop pointing to `2.0.2`, then they should point to the final location instead of a meta-refresh.

**Comment by jklymak** [comment]
I'd say again, its not really worth the extra hassle?  Folks get where they want to eventually, and will ideally not be linking old pages.  

Conversely, I guess we could check the contents of the html for the refresh, but...

**Comment by QuLogic** [comment]
Well, in this case, I'm not worried about people getting there, but about the effect on canonicalization for search engines and whether it breaks something due to not pointing at the final page.

**Comment by jklymak** [comment]
I don't *think* thats a problem.  In general we only want the web search to reach the canonical `stable/`, and other links should be discouraged on the search engines anyway...  Its *possible* we will get some sort of penalty on the search terms, so we should keep an eye on that, but I'm not too concerned so long as "customizing matplotlib" gives us `https://matplotlib.org/stable/tutorials/introductory/customizing.html` as a top-level search....

But again, I'm no expert on SEO, so if this is really a problem we could get fancier...

**Comment by QuLogic** [comment]
For now, I've committed the changes when adding 3.4.1 docs. If it is an SEO problem, then we can modify this a bit.

**Comment by QuLogic** [comment]
Let's leave this as is. At least the double-redirects get to the right place eventually.
