### ISSUE TITLE
/index.html is currently redirected to /stable/index.html

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib.github.com#63]
For the 3.5.0 push /index.html is currently redirected to /stable/index.html 

I think the plan was to move mpl-brochure-site/index.html to here.  Maybe the redirect script needs to be updated?  Maybe the release notes need to be updated?

**Comment by QuLogic** [comment]
Actually, I just forgot about this when doing the redirect script. However, it looks like @tacaswell has moved the brochure site over, so we can close this.
