### ISSUE TITLE
download and install matplotlib in NVIDIA TX2

### ISSUE THREAD

**Issue by Overture-Y** [matplotlib/matplotlib.github.com#64]
I want to load and install matplotlib in NVIDIA TX2 with archiconda, but if I install it with "pip3 install matplotlib==3.3.4", the package only can be download, can‘t be installed, if I install with "conda install matplotlib==3.3.4", the package can install successfully, but I can't import packages,there is a example: 
>>>python3
>>>import matplotlib
illegal instruction(core dump)

Note: I tried add "export OPENBLAS_CORETYPE=ARMV8"  into ~/.bashrc, but there is no help.
Can you help me to solve this problems?

**Comment by jklymak** [comment]
Please discuss install problems on discourse.matplotlib.org. Thanks
