### ISSUE TITLE
First google result for "matplotlib gallery" goes to stale link

### ISSUE THREAD

**Issue by scottshambaugh** [matplotlib/matplotlib.github.com#66]
When I want to find the matplotlib gallery, the first google result is https://matplotlib.org/gallery.html
![image](https://user-images.githubusercontent.com/14363975/147288771-ab594881-e1bb-4b92-a172-ff731d6bc238.png)

This redirects to https://matplotlib.org/2.0.2/gallery.html , which prompts me to click through to the stable docs:
![image](https://user-images.githubusercontent.com/14363975/147288869-22c3b7c2-c573-4e9c-b527-8ca0dbf1e98c.png)

However that leads me to https://matplotlib.org/stable/ and I have to hunt for the link to the gallery on that page. As a familiar user this chain of several clicks is annoying, and I imagine that to a new user this is extremely confusing. Or they would miss the banner and stay on the old documentation site. 

So, three points here:
1) Is there a reason the gallery redirect goes to the old docs?
2) This may be an issue with other top-level urls and could use an audit, I haven't checked others.
3) Is there a way of redirecting to the corresponding stable documentation page from the old docs (if it exists), rather than to the documentation main page?

**Comment by QuLogic** [comment]
This might take a little while to get through all caches, but this should redirect to the current gallery now.

**Comment by scottshambaugh** [comment]
This issue is still showing up for me, even with a fresh browser.

**Comment by QuLogic** [comment]
@tacaswell Can you make sure the CloudFlare cache is cleared?

**Comment by QuLogic** [comment]
So actually, GitHub changed how it does deployment and our site is over the 10GB limit again.
