### ISSUE TITLE
No canonical links 3.5.0 and 3.5.1

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib.github.com#68]
We want the header of the current docs to point to the stable docs as canonical so search engines find those: `<link rel="canonical" href="https://matplotlib.org/stable/index.html" />`.  This didn't happen for 3.5.0 and 3.5.1.  Not sure if the fix is a doc-release python script or a fix to the doc build.    Note that we have `make_redirects_links.py` that added the link to 3.4 and earlier, but I guess we don't want to run that whole hassle each time.

**Comment by QuLogic** [comment]
I didn't run that because we wanted to stop adding new things to the root that were just extra copies that were immediately 'deprecated'. If there's a way to just add the canonical URL, whether with the script or in the default doc build, that'd be better.
