### ISSUE TITLE
3.5.0 is trending above stable in google search

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib.github.com#72]
`3.5.0` somehow does not have the "canonical" links in the header, so it is not often trending above `stable` in google search.  Probably worth running the script to fix this?  

New pages (3.5.1, and those on 3.5.2) have the correct canonical, as do all the old ones....

3.5.1 and 3.5.0 do not have a "old version of Matplotlib" banner, however.  Do we want that?

**Comment by QuLogic** [comment]
Oh, I had fixed this about a month ago, b25285946a9a13aa686d7f4933cb10dcdce1c1eb, but the server was on the wrong branch and so didn't refresh. We should be preferring `stable` again now.

**Comment by QuLogic** [comment]
I re-ran the script, but it only updated some old/incorrect redirects and did not add a banner to 3.5.0/3.5.1; maybe there was a change in the theme and it no longer finds its insertion point?

**Comment by jklymak** [comment]
Search results are all topped by stable again!  I think we can close this....
